#!/usr/bin/env python

from collections import defaultdict
from billy import db
import json
import sys

state = sys.argv[1]
breakup = 100000

breakdown = {}
numcount = defaultdict(int)
total_legs = 0
total_raised = 0
min_total = None
max_total = None

legislators = db.legislators.find({"state": state})
for leg in legislators:
    if not "_total_contributions" in leg:
        continue

    raised = leg['_total_contributions']
    cat = (raised / breakup)
    breakdown[leg['leg_id']] = cat
    total_legs += 1
    total_raised += raised
    if not min_total or raised < min_total:
        min_total = raised

    if not max_total or raised > max_total:
        max_total = raised

avg = (total_raised / total_legs)

red = defaultdict(int)
for entry in breakdown:
    red[breakdown[entry]] += 1

print "min:", min_total
print "max:", max_total
print "avg:", avg
print "red:", red
#print json.dumps(breakdown, sort_keys=True, indent=4)
